version: '3'
services:

  prometheus:
    image: prom/prometheus:v2.47.2
    container_name: ivanozhigov-netology-prometheus
    command: --web.enable-lifecycle --config.file=/home/ivanozhigov
    ports:
      - 19090:9090
    volumes:
      - /etc/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitoring-stack
    restart: always

  pushgateway:
    image: prom/pushgateway:v1.6.2
    container_name: ivanozhigov-netology-pushgateway
    ports:
      - 9091:9091
    networks:
      - monitoring-stack
    restart: unless-stopped



  grafana:
    image: grafana/grafana
    container_name: ivanozhigov-netology-grafana
    environment:
      GF_PATHS_CONFIG: /etc/grafana/custom.ini
    ports:
      - 80:3000
    volumes:
      - /etc/grafana/custom.ini:/etc/grafana/custom.ini
      - grafana-data:/var/lib/grafana
    networks:
      - monitoring-stack
    restart: unless-stopped
volumes:
  grafana-data:

networks:
  monitoring-stack:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
